var quotes = [
            {
              text: 'With great power comes great responsibility.',
              source: 'Uncle Ben',
              citation: 'Spider-Man',
              year: '2002',
              tags: 'Movies/Comics',
            },
            {
              text: "If you ain't first, you're last.",
              source: 'Ricky Bobby',
              citation: 'Talladega Nights',
              year: '2006',
              tags: 'Movies/Comedy',
            },
            {
              text: 'You stay classy, San Diego.',
              source: 'Ron Burgundy',
              citation: 'Anchorman',
              year: '2004',
              tags: 'Movies/Comedy',
            },
            {
              text: 'Nothing you have not given away will ever really be yours.',
              source: 'C.S. Lewis',
              citation: 'Mere Christianity',
              year: '1952',
              tags: 'Christianity',
            },
            {
              text: 'Friendship is born at that moment when one person says to another: "What! You too? I thought I was the only one.',
              source: 'C.S. Lewis',
              citation: 'The Problem of Pain',
              year: '1940',
              tags: 'Christianity',
            },
            {
              text: "In our own case we accept excuses too easily; in other people's, we do not accept them easily enough.",
              source: 'C.S. Lewis',
              citation: 'The Weight of Glory',
              year: '1949',
              tags: 'Christianity',
            },
            {
              text: "You ain't cool unless you pee your pants.",
              source: 'Billy Madison',
              citation: 'Billy Madison',
              year: '1995',
              tags: 'Movies/Comedy',
            },
            {
              text: 'Please get out of my Van Halen t-shirt before you jinx the band and they break up.',
              source: 'Robby Heart',
              citation: 'The Wedding Singer',
              year: '1998',
              tags: 'Movies/Comedy',
            },
            {
              text: 'Yeah, I can fly.',
              source: 'Tony Stark',
              citation: 'Iron Man',
              year: '2008',
              tags: 'Movies/Comics',
            },
            {
              text: 'Some are born great, some achieve greatness, and some have greatness thrust upon them.',
              source: 'William Shakespeare',
              citation: 'Twelfth Night',
              year: '1601',
              tags: 'Inspirational',
            },
            {
              text: 'Life is either a daring adventure or nothing at all.',
              source: 'Helen Keller',
              citation: 'Let Us Have Faith',
              year: '1940',
              tags: 'Inspirational',
            },
            {
              text: 'The greatest weapon against stress is our ability to choose one thought over another.',
              source: 'William James',
              tags: 'Inspirational',
            }
            ];
